### PR TITLE
Give up on Zendesk finalization if Secret is not found

### LINKED ISSUE #77: Zendesk: give up on finalization if Secret is not found
In case the user deletes the secret containing the Zendesk API token _before_ deleting the source itself, the finalizer will fail forever on the error
```
secrets "zendesksource" not found
```
preventing the object from being deleted.

### PR DESCRIPTION
**Pull request by antoineco**
Fixes #77

### CODE REVIEW

File: pkg/reconciler/zendesksource/zendesk.go [hunk 1]
```diff
@@ -181,11 +181,21 @@ func (r *Reconciler) ensureNoZendeskTargetAndTrigger(ctx context.Context) error
 
 	src := v1alpha1.SourceFromContext(ctx)
 
+	title := targetTitle(src)
```
Comment (cab105) [inline pkg/reconciler/zendesksource/zendesk.go:184]: Why migrate the `targetTitle`?

Comment (antoineco) [reply pkg/reconciler/zendesksource/zendesk.go:184]: So it can be logged in the event right below.
